import type {
  Ad,
  AdSet,
  AutomationRule,
  Campaign,
  KpiMetric,
  OptimizationStrategy,
  Suggestion,
} from '@/types/dashboard';

export const mockKpiMetrics: KpiMetric[] = [
  {
    id: 'spend',
    label: 'Total Spend',
    value: '₺12,340',
    trend: '+12%',
    status: 'up',
    description: 'Last 7 days Meta spend.',
  },
  {
    id: 'roas',
    label: 'ROAS',
    value: '3.20',
    trend: '+4%',
    status: 'up',
    description: 'Last 7 days average ROAS.',
  },
  {
    id: 'conversions',
    label: 'Conversions',
    value: '46',
    trend: '+9%',
    status: 'up',
    description: 'Purchase/lead conversions.',
  },
  {
    id: 'ctr',
    label: 'CTR',
    value: '1.20%',
    trend: '-2%',
    status: 'down',
    description: 'Click-through rate (average).',
  },
];

export const mockSuggestions: Suggestion[] = [
  {
    id: 's1',
    title: 'Pause low-CTR ads',
    description: 'Ads with CTR below 1% for 3 days detected.',
    impactLevel: 'High',
    impactMetric: '+12% ROAS potential',
    action: {
      type: 'pause',
      label: 'Pause Ad',
      details: 'This ad will be paused and spend will stop.',
      currentValue: 'Active',
      newValue: 'Paused',
    },
    target: { level: 'ad', id: 'ma2', name: 'Feed_Image_v3' },
  },
  {
    id: 's2',
    title: 'Scale winning ad sets',
    description: 'Safely increase daily budget on high-ROAS ad sets.',
    impactLevel: 'Medium',
    impactMetric: '+8% conversion potential',
    action: {
      type: 'increase_budget',
      label: 'Increase Budget 20%',
      details: 'Daily budget will increase from ₺250 to ₺300.',
      currentValue: '₺250/day',
      newValue: '₺300/day',
    },
    target: { level: 'adset', id: 'mas1', name: 'Women 25-34' },
  },
  {
    id: 's3',
    title: 'Creative fatigue check',
    description: 'Performance drop detected in creatives with frequency > 4.',
    impactLevel: 'Medium',
    impactMetric: '+6% CTR potential',
    action: {
      type: 'review',
      label: 'Review & Fix',
      details: 'Creative should be refreshed or audience changed.',
      currentValue: 'Frequency: 4.2',
      newValue: 'Target: < 3.0',
    },
    target: { level: 'campaign', id: 'mc2', name: 'Prospecting - Lead' },
  },
];

export const mockMetaCampaigns: Campaign[] = [
  { id: 'mc1', name: 'Retargeting - Sales', status: 'active', spend: '₺12,400', roas: '3.20', conversions: 46 },
  { id: 'mc2', name: 'Prospecting - Lead', status: 'active', spend: '₺8,950', roas: '1.85', conversions: 19 },
  { id: 'mc3', name: 'Catalog - Conversions', status: 'paused', spend: '₺3,120', roas: '2.10', conversions: 7 },
];

export const mockMetaAdSets: AdSet[] = [
  {
    id: 'mas1',
    name: 'Women 25-34',
    status: 'active',
    campaignId: 'mc1',
    campaignName: 'Retargeting - Sales',
    bidStrategy: 'lowest_cost',
    dailyBudget: '₺250',
    spend: '₺3,600',
    roas: '2.10',
    conversions: 11,
  },
  {
    id: 'mas2',
    name: 'Men 25-44',
    status: 'paused',
    campaignId: 'mc2',
    campaignName: 'Prospecting - Lead',
    bidStrategy: 'cost_cap',
    dailyBudget: '₺180',
    spend: '₺1,240',
    roas: '1.20',
    conversions: 3,
  },
];

export const mockMetaAds: Ad[] = [
  {
    id: 'ma1',
    name: 'Story_Video_v1',
    status: 'active',
    adSetId: 'mas1',
    adSetName: 'Women 25-34',
    previewUrl: 'https://example.com/preview/ma1',
    ctr: '1.2%',
    spend: '₺420',
    roas: '1.80',
    conversions: 2,
  },
  {
    id: 'ma2',
    name: 'Feed_Image_v3',
    status: 'paused',
    adSetId: 'mas2',
    adSetName: 'Men 25-44',
    previewUrl: 'https://example.com/preview/ma2',
    ctr: '0.8%',
    spend: '₺190',
    roas: '0.90',
    conversions: 0,
  },
];

export const mockAutomationRules: AutomationRule[] = [
  {
    id: '1',
    title: 'Pause ads if CTR is low',
    condition: 'CTR < 1.0% (last 3 days)',
    action: 'Pause ads',
    frequency: 'Real-time',
    executionCount: 12,
    status: 'active',
    iconCategory: 'pause',
    source: 'template',
    templateId: 'tpl_ctr_pause_ads',
  },
  {
    id: '2',
    title: 'Pause ads if ROAS is low',
    condition: 'ROAS < 1.2 (last 3 days)',
    action: 'Pause ads',
    frequency: 'Daily',
    executionCount: 8,
    status: 'active',
    iconCategory: 'alert',
    source: 'template',
    templateId: 'tpl_roas_pause_ads',
  },
  {
    id: '3',
    title: 'Pause ad set if spend limit exceeded',
    condition: 'Spend > ₺2,000 (today)',
    action: 'Pause ad set',
    frequency: 'Real-time',
    executionCount: 45,
    status: 'scheduled',
    iconCategory: 'budget',
    source: 'template',
    templateId: 'tpl_spend_cap_pause_adset',
  },
  {
    id: '4',
    title: 'Pause ads if CTR is low',
    condition: 'CTR < 1.0% (last 3 days)',
    action: 'Pause ads',
    frequency: '-',
    executionCount: 0,
    status: 'paused',
    iconCategory: 'pause',
    source: 'template',
    templateId: 'tpl_ctr_pause_ads',
  },
];

export const mockOptimizationStrategies: OptimizationStrategy[] = [
  {
    id: '1',
    title: 'Pause Low-CTR Ads',
    description: 'Detects long-running ads with low CTR and suggests pausing them.',
    status: 'paused',
    iconCategory: 'performance',
  },
  {
    id: '2',
    title: 'High CPC / CPM Optimization',
    description: 'Finds ad sets with click costs above target threshold and suggests budget reduction.',
    status: 'paused',
    iconCategory: 'budget',
  },
  {
    id: '3',
    title: 'Creative Fatigue (Frequency > 4)',
    description: 'Detects ads with frequency above 4 and declining performance.',
    status: 'paused',
    iconCategory: 'creative',
  },
  {
    id: '4',
    title: 'Scale Winners',
    description: 'Suggests safe budget increases for high-ROAS, high-CTR ad sets (without exceeding 20% daily limit).',
    status: 'paused',
    iconCategory: 'budget',
  },
  {
    id: '5',
    title: 'AI Creative Analysis',
    description: 'Scores visuals with AI (0-100). Suggests refreshing creatives scoring below 60.',
    status: 'paused',
    iconCategory: 'creative',
  },
  {
    id: '6',
    title: 'AI Budget Allocation',
    description: 'Automatically shifts budget from low-performing campaigns to highest-return ones.',
    status: 'paused',
    iconCategory: 'budget',
  },
  {
    id: '7',
    title: 'Account Health Score',
    description: 'Analyzes your account 360°. Provides critical fix suggestions if health score drops below 70.',
    status: 'paused',
    iconCategory: 'health',
  },
];
